# Generated by Django 3.0.8 on 2020-08-01 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100, verbose_name='Название')),
                ('article_text', models.TextField(verbose_name='Текст')),
                ('article_create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('article_published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение')),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
